#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -Werror -I$(srctree)/drivers/misc/mediatek/lcm/inc

ccflags-y += -Wno-unused-variable -g
ccflags-y += -Wno-unused-function -g

ccflags-y += -Werror

obj-y += otm1284a_hd720_dsi_vdo_baolongda.o




