#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

ccflags-y += -Wno-unused-variable -g
ccflags-y += -Wno-unused-function -g

obj-y += ili9881_hd720_dsi_vdo_yassy.o



